export const categories_names = [
  "biryanis",
  "veg_curries",
  "soups",
  "tandoori",
  "non_veg_curries",
  "fried_rice",
  "nonveg_starters",
  "veg_starters",
  "papads",
  "grill_items",
  "salads",
  "beverages",
  "veg_fried_rice",
  "nonveg_fried_rice",
  "naans_rotis",
  "veg_indian_curriees",
  "nonveg_indian_curries",
  "veg_biryani",
];

export const recipes = {
  restaurant0: {
    name: "vinay biryanis",
    biryanis: [
      ["dum biryani half", 130],
      ["dum biryani full", 200],
      ["dum biryani family", 250],
      ["fry piece biryani half", 130],
      ["fry piece biryani full", 180],
      ["fry piece biryani family", 250],
    ],
  },
  restaurant1: {
    name: "vindhu family restaruant",
    veg_curries: [
      ["paneer butter masala", 220],
      ["mushroom curry", 220],
      ["methi chaman", 230],
      ["paneer kaaju curry", 250],
      ["mushroom kaaju", 250],
      ["three step curry", 250],
      ["kaaju masala", 240],
      ["kaaju tomato", 230],
      ["veg mixed curry", 180],
      ["veg navabhi", 200],
    ],
    soups: [
      ["veg sweet corn soup", 100],
      ["mushroom keema soup", 100],
      ["chicken corn soup", 130],
      ["chicken hot sour soup", 120],
    ],
    tandoori: [
      ["batti kabab", 100],
      ["chicken gaint", 130],
      ["1/2 tandoori", 260],
      ["full tandoori", 500],
      ["chicken tikka", 300],
      ["hyderabad tikka", 320],
      ["malai tikka", 320],
      ["butter naan", 60],
      ["garlic naan", 90],
      ["methi roti", 120],
      ["tandoori roti", 40],
      ["plain naan", 40],
      ["pulka", 8],
    ],
    non_veg_curries: [
      ["doopudu pothu flesh curry", 380],
      ["pacchi royyala kodi kura iguru", 350],
      ["thala kaya curry", 270],
      ["seelavathi chepa pulusu", 150],
      ["mutton curry", 380],
      ["chicken curry(bone)", 230],
      ["prawns curry", 340],
      ["boneless chicken curry", 260],
      ["chicken navabhi", 280],
      ["hyderabad chicken curry", 280],
      ["murgh masala", 300],
      ["tikka masala", 320],
      ["kaaju pitta curry", 200],
      ["dhamka curry full", 300],
      ["butter chicken", 280],
      ["egg burri", 160],
      ["anda mughlai", 160],
      ["chicken mughlai curry", 280],
    ],
    biryanis: [
      ["chicken dum biryani (pot)", 300],
      ["chicken fry peace biryani", 250],
      ["chicken mughlai biryani", 300],
      ["prawns biryani", 360],
      ["mutton biryani", 400],
      ["dum mughlai biryani", 330],
      ["guntoor chicken biryani", 320],
      ["avakay chicken biryani", 320],
      ["mixed biryani", 370],
      ["mixed mughlai biryani", 380],
      ["prawns mughlai biryani", 380],
      ["mutton mughlai biryani", 420],
      ["chicken special biryani", 320],
      ["mushroom biryani", 300],
      ["veg biryani", 180],
      ["veg mughlai biryani", 290],
      ["three star biryani", 300],
      ["egg biryani", 220],
    ],
    fried_rice: [
      ["veg fried rice", 180],
      ["veg fried rice special", 260],
      ["veg mughlai fried rice", 280],
      ["mushroom fried rice", 300],
      ["three star fried rice", 300],
      ["kaaju fried rice", 300],
      ["egg fried rice", 200],
      ["egg mughlai fried rice", 230],
      ["egg manchuria fried rice", 250],
      ["chicken fried rice", 250],
      ["chicken special fried rice", 300],
      ["mughlai fried rice", 300],
      ["mixed fried rice", 370],
      ["prawns fried rice", 360],
      ["mutton fried rice", 400],
      ["fry piece fried biryani", 250],
      ["gongura chicken fried rice", 330],
    ],
    nonveg_starters: [
      ["chilli chicken", 290],
      ["rr chicken", 290],
      ["lemon chicken", 290],
      ["chicken-65", 290],
      ["sathayi chicken", 320],
      ["kasturi chicken", 300],
      ["kabab", 90],
      ["mughlai kabab", 100],
      ["kashmir kabab", 100],
      ["fried wings", 270],
      ["chilli wings", 300],
      ["chicken lollipop", 300],
      ["kaaju pitta fry", 200],
      ["loose prawns", 360],
      ["prawns fry", 360],
      ["fish fry", 350],
      ["chilli egg", 200],
      ["kaaju chicken", 370],
      ["mutton fry", 400],
      ["crab pakodi", 320],
      ["chicken 555", 350],
      ["bangla kodi fry", 320],
      ["fish chips", 370],
      ["chicken chips", 370],
      ["stick prawns", 420],
      ["mutton ghee roast", 420],
    ],
    veg_starters: [
      ["chilli mushroom", 250],
      ["chilli paneer", 250],
      ["paneer 65", 250],
      ["veg spring roast", 220],
      ["veg manchuria", 220],
      ["sweet corn pakodi", 200],
      ["fever kaaju", 240],
      ["three step pakodi", 300],
      ["bangla paneer", 270],
    ],
  },
  restaurant2: {
    name: "sri bhaskara",
    soups: [
      ["veg hot & sour soup", 100],
      ["veg sweet corn soup", 100],
      ["veg manchow soup", 100],
      ["veg lemon coriander soup", 100],
      ["tomato soup", 100],
      ["non veg hot & sour soup", 130],
      ["non veg sweet corn soup", 130],
      ["non veg manchow soup", 130],
      ["non veg lemon coriander soup", 130],
      ["cream of mushroom soup", 100],
      ["cream of chicken soup", 130],
    ],
    papads: [
      ["masala papad", 45],
      ["roasted papad", 35],
    ],
    grill_items: [
      ["vanjaram tandoori", 450],
      ["half alfaham chicken", 280],
      ["full alfaham chicken", 550],
      ["half grill chicken", 280],
      ["full grill chicken", 550],
    ],
    salads: [
      ["cucumber salad", 100],
      ["green salad", 100],
      ["curd", 40],
      ["curd rice", 100],
      ["sp curd rice", 130],
    ],
    beverages: [
      ["cool drink", 25],
      ["water bottle", 25],
      ["soda", 20],
      ["badam milk 1lt", 150],
      ["buttermilk", 40],
      ["lemon soda", 40],
      ["lassi (sweet/salt)", 60],
    ],
    veg_starters: [
      ["rr veg", 220],
      ["crispy veg", 220],
      ["dragon veg", 220],
      ["veg manchurian", 220],
      ["cashew fry", 240],
      ["paneer majestic", 240],
      ["chilli paneer", 240],
      ["paneer manchurian", 240],
      ["chilli paneer", 240],
      ["garlic paneer", 240],
      ["paneer 65", 240],
      ["chilli baby corn", 240],
      ["baby corn manchurian", 240],
      ["crispy baby corn", 240],
      ["chilli mushroom", 240],
      ["mushroom manchurian", 240],
      ["mushroom (salt & pepper)", 240],
      ["mushroom 65", 240],
      ["paneer tikka", 250],
    ],
    nonveg_starters: [
      ["chilli chicken", 330],
      ["chicken manchurian", 330],
      ["chicken 65", 330],
      ["garlic chicken", 330],
      ["rr chicken", 330],
      ["schezwan chicken", 330],
      ["dragon chicken", 330],
      ["hongkong chicken", 330],
      ["cashewnut chicken", 330],
      ["chicken dry roast", 330],
      ["crispy chicken", 330],
      ["pepper chicken", 330],
      ["oil kabab", 90],
      ["chilli kabab", 100],
      ["mogalai kabab", 120],
      ["chicken lollypops (dry)", 300],
      ["chicken lollypops (wet)", 320],
      ["chicken liver fry", 180],
      ["chicken fry (bone)", 180],
      ["chicken fry (boneless)", 270],
      ["chicken majestic", 330],
      ["tandoori chicken (half)", 280],
      ["tandoori chicken (full)", 540],
      ["tangdi kabab - 4 pcs", 360],
      ["chicken tikka - 8 pcs", 320],
      ["mutton fry", 390],
      ["chilly mutton", 390],
      ["mutton manchurian", 390],
      ["mutton 65", 390],
      ["rr mutton", 390],
      ["ginger mutton", 390],
      ["garlic mutton", 390],
      ["chilly egg", 200],
      ["egg manchurian", 200],
      ["egg 65", 200],
      ["chilly prawns", 340],
      ["prawns fry", 340],
      ["prawns manchurian", 340],
      ["prawns 65", 340],
      ["garlic prawns", 340],
      ["ginger prawns", 340],
      ["prawns salt & pepper", 340],
      ["loose prawns", 340],
      ["dragon prawns", 340],
      ["apolo fish", 340],
      ["chilly fish", 340],
      ["fish manchurian", 340],
      ["fish 65", 340],
      ["fish schezwan", 340],
      ["fish fry", 340],
      ["dry roast", 340],
      ["fish majestic", 340],
      ["mangolian fish", 340],
    ],
    veg_fried_rice: [
      ["veg fried rice", 170],
      ["veg sp fried rice (mushroom curry)", 240],
      ["veg sp fried rice (paneer curry)", 240],
      ["veg sp mogalai fried rice (mushroom curry)", 270],
      ["veg sp mogalai fried rice (paneer curry)", 270],
      ["jeera rice", 170],
      ["schezwan veg fried rice", 200],
      ["veg corn fried rice", 200],
      ["veg garlic fried rice", 200],
      ["corn & cashewnut fried rice", 260],
    ],
    nonveg_fried_rice: [
      ["chicken fried rice", 200],
      ["prawns fried rice", 300],
      ["mutton fried rice", 340],
      ["chicken sp fried rice", 280],
      ["prawns sp fried rice", 350],
      ["mutton sp fried rice", 380],
      ["chicken fry piece fried rice", 250],
      ["chicken mogalai fried rice", 270],
      ["prawns mogalai fried rice", 340],
      ["mutton mogalai fried rice", 380],
      ["schezwan chicken fried rice", 240],
      ["mixed fried rice", 320],
      ["mixed mogalai fried rice", 350],
      ["egg fried rice", 180],
      ["sp egg fried rice", 250],
      ["schezwan egg fried rice", 200],
    ],
    nanns_rotis: [
      ["pulkha (only evening)", 10],
      ["butter pulkha (only evening)", 15],
      ["plain naan", 50],
      ["butter naan", 60],
      ["plain roti", 40],
      ["butter roti", 45],
      ["plain kulcha", 70],
      ["masala kulcha", 80],
      ["moghalai naan", 100],
      ["garlic naan", 80],
      ["aloo paratha", 90],
    ],
    veg_indian_curriees: [
      ["mix veg curry", 180],
      ["kadai veg curry", 200],
      ["veg kolapuri", 220],
      ["veg jaipuri", 220],
      ["paneer butter masala", 200],
      ["tomato cashew curry", 240],
      ["paneer cashew curry", 240],
      ["plain cashew curry", 240],
      ["mushroom kadai curry", 220],
      ["paneer kadai curry", 220],
      ["paneer mushroom curry", 240],
      ["mushroom cashew curry", 240],
      ["green peas masala", 160],
      ["paneer tikka masala", 240],
      ["methi chaman curry", 230],
      ["rasmalai curry", 220],
      ["babycorn masala curry", 220],
      ["mushroom masala", 220],
      ["veg chatpat curry", 200],
    ],
    nonveg_indian_curries: [
      ["chicken curry (bone)", 220],
      ["chicken curry (boneless)", 220],
      ["methi chicken", 200],
      ["butter chicken", 230],
      ["kadai chicken", 260],
      ["cashew chicken", 280],
      ["chicken mogalai curry", 300],
      ["kabab masala", 280],
      ["chicken tikka masala", 300],
      ["liver curry", 300],
      ["andhra chicken curry", 240],
      ["chicken chatnadu", 300],
      ["chicken maharani", 200],
      ["punjabi chicken", 260],
      ["mutton curry", 300],
      ["gongura mutton", 300],
      ["mutton keema curry", 300],
      ["mutton rogan josh", 350],
      ["kadai mutton", 380],
      ["mutton masala", 400],
      ["Gongura Prawns Curry", 320],
      ["Prawns Masala", 280],
      ["Fish Masala", 280],
      ["Egg Curry", 180],
      ["Egg Mogalai Curry", 200],
    ],
    veg_biryani: [
      ["Veg Biryani", 180],
      ["Veg Sp Biryani (Mushroom Curry)", 250],
      ["Veg Sp Biryani (Paneer Curry)", 250],
      ["Paneer Biryani", 280],
      ["Cashew Biryani", 280],
      ["Mushroom Biryani", 280],
      ["Veg Mixed Mogalai Biryani", 260],
      ["Veg Sp Mogalai Biryani (Paneer)", 300],
      ["Veg Sp Mogalai Biryani (Mushroom)", 300],
    ],
    nonveg_biryani: [
      ["Chicken Fry Bit Biryani", 240],
      ["Pot Biryani", 300],
      ["Chicken Sp Biryani", 280],
      ["Prawns Sp Biryani", 340],
      ["Mutton Sp Biryani", 400],
      ["Kabab Biryani", 320],
      ["Aavakayi Chicken Biryani", 300],
      ["Vulavacharu Chicken Biryani", 300],
      ["Chicken Moghalai Biryani", 300],
      ["Prawns Moghalai Biryani", 340],
      ["Mutton Moghalai Biryani", 400],
      ["Mixed Biryani", 320],
      ["Liver Biryani", 260],
      ["Dilkush Biryani", 400],
      ["Mixed Mogalai Biryani", 350],
      ["Egg Biryani", 200],
      ["Sp Egg Biryani", 250],
      ["Mutton Biryani", 360],
      ["Mutton Keema Biryani", 380],
      ["Prawns Biryani", 320],
      ["Fish Biryani (Boneless)", 320],
      ["Potlam Biryani", 380],
      ["Tandoori Biryani", 400],
    ],
    ice_creams: [
      ["Vanilla (2 Scoops)", 80],
      ["Strawberry (2 Scoops)", 80],
      ["Blackcurrant (2 Scoops)", 100],
      ["Butterscotch (2 Scoops)", 130],
      ["Chocolate (2 Scoops)", 130],
      ["American Dry Fruit (2 Scoops)", 140],
      ["Caramel Nuts (2 Scoops)", 150],
      ["Sithapal (2 Scoops)", 100],
      ["Sapota (2 Scoops)", 90],
      ["Jackfruit (2 Scoops)", 100],
      ["TenderCoconut (2 Scoops)", 120],
      ["Blueberry (2 Scoops)", 110],
      ["Pineapple (2 Scoops)", 80],
      ["Kiwi (2 Scoops)", 90],
    ],
    kulfi_cones: [
      ["Malai Kulfi", 25],
      ["Rajbhoj Kulfi", 30],
      ["Matka Kulfi", 60],
      ["Chocochips Cone", 40],
      ["Strawberry Cone", 30],
      ["Butterscotch Cone", 40],
      ["Choco Cookie Cone", 45],
      ["Badam Roasted Cone", 50],
      ["Fruit Salad", 100],
      ["Fruit Salad with Icecream (Vanilla)", 140],
    ],
    mocktails: [
      ["Lemon Mojito", 120],
      ["Orange Mojito", 120],
      ["Mint Mojito", 120],
      ["Mosambi Mojito", 120],
      ["Pineapple Mojito", 120],
      ["Watermelon Mojito", 120],
      ["Greenapple Mojito", 120],
      ["Kiwi Mojito", 120],
      ["Blue Mojito", 120],
      ["Guava Mojito", 120],
      ["Grape Mojito", 120],
      ["Fruit Punch", 140],
      ["Perfect Lady", 140],
      ["Blue Loogan", 120],
      ["Blossom Ice", 120],
      ["Green Cooler", 120],
      ["Raspberry Mojito", 120],
    ],
    juice_milkshake: [
      ["Watermelon Juice", 60],
      ["Apple Juice", 70],
      ["Grape Juice", 70],
      ["Pineapple Juice", 70],
      ["Kharbuja Juice", 70],
      ["Papaya Juice", 70],
      ["Banana Juice", 70],
      ["Promogranate Juice", 100],
      ["Lemon Juice", 40],
      ["Vanilla Milkshake", 150],
      ["Strawberry Milkshake", 150],
      ["Blackcurrant Milkshake", 150],
      ["Chocolate Milkshake", 150],
      ["Butterscotch Milkshake", 150],
      ["Caramel Milkshake", 150],
      ["American Nuts Milkshake", 180],
      ["Dry Fruit Milkshake", 200],
    ],
    falooda: [
      ["rose falooda", 110],
      ["dry fruit falooda", 150],
      ["fruit special falooda", 150],
      ["bhaskar special falooda", 180],
    ],
  },
  restaurant3: {
    name: "new biryanis",
    biryanis: [
      ["chicken mughlai biryani", 200],
      ["chicken fried mughlai biryani", 200],
      ["chicken boneless biryani", 220],
      ["avakai chicken mughlai biryani", 250],
      ["gongura chicken mughlai biryani", 250],
      ["mutton biryani", 220],
      ["mutton mughlai biryani", 250],
      ["mutton keema mughlai biryani", 300],
      ["mutton kaaju biryani", 350],
      ["new special mutton biryani", 350],
      ["new special mix chicken mughlai biryani", 550],
    ],
    veg_curries: [
      ["mix veg curry", 100],
      ["kadai veg curry", 120],
      ["veg kurma curry", 150],
      ["veg jayapuri curry", 150],
      ["veg chatpat curry", 200],
      ["paneer curry", 150],
      ["paneer butter masala curry", 170],
      ["paneer tadka curry", 180],
      ["paneer dopyaja curry", 200],
      ["methi chaman curry", 200],
      ["kadai paneer curry", 200],
      ["kaaju paneer curry", 150],
      ["kaaju tomato curry", 170],
      ["kaaju masala curry", 170],
      ["kaaju butter curry", 200],
      ["butter paneer curry", 200],
    ],
    veg_fried_rice: [
      ["veg fried rice", 100],
      ["veg sp fried rice", 150],
      ["veg green butter fried rice", 150],
      ["veg green butter paneer fried rice", 150],
      ["paneer fried rice", 200],
      ["veg schezwan fried rice", 150],
      ["veg tomato fried rice", 200],
    ],
    nonveg_curries: [
      ["chicken boneless curry", 200],
      ["butter chicken curry", 200],
      ["chicken mughlai curry", 200],
      ["chicken dopyaji curry", 200],
      ["punjab chicken curry", 200],
      ["chicken lajavab curry", 200],
      ["chicken bengaluru curry", 200],
      ["kadai chicken curry", 200],
      ["chicken kaaju curry", 200],
      ["andhra chicken curry", 200],
      ["mutton curry", 200],
      ["prawns curry", 200],
    ],
    rice: [
      ["veg meals(single)", 70],
      ["veg meals(double)", 90],
      ["curd rice", 60],
      ["tomato rice", 100],
      ["jeera rice", 100],
      ["vammu rice", 100],
      ["lemon rice", 100],
    ],
    nonveg_rice: [
      ["chicken fried rice", 160],
      ["chicken schezwan fried rice", 200],
      ["chicken hakka fried rice", 220],
      ["chicken kandari fried rice", 220],
      ["chicken singapore fried rice", 220],
      ["chicken christmas fried rice", 220],
      ["achari chicken fried rice", 250],
      ["baby chicken fried rice", 250],
      ["egg chicken fried rice", 120],
      ["new biryani special chicken fried rice", 550],
    ],
    chicken_starters: [
      ["ginger chicken", 200],
      ["special chicken", 200],
      ["chicken 65", 200],
      ["chicken manchuria", 200],
      ["chilli chicken", 180],
      ["schezwan chicken", 200],
      ["garlic chicken", 200],
      ["chicken mongolian", 200],
      ["chicken thiawa", 200],
      ["red hot chicken", 200],
      ["spicy chicken", 200],
      ["chicken majestic", 200],
      ["achari chicken", 200],
      ["rr chicken", 200],
      ["rrra chicken", 250],
      ["chicken lollipop", 180],
      ["chicken joint", 100],
      ["mughlai kabab", 100],
      ["batti kabab", 70],
      ["rumal roti", 20],
      ["pulka", 5],
    ],
    veg_starters: [
      ["veg manchuria", 100],
      ["veg 65", 120],
      ["veg chilli", 150],
      ["paneer 65", 200],
      ["paneer manchuria", 200],
      ["paneer chilli", 200],
      ["schezwan paneer", 250],
      ["potato 65", 100],
    ],
  },
  restaurant4: {
    name: "Bakery",
    cakes: [
      ["cake (500gm)", 170],
      ["cake (1kg)", 300],
      ["cool cake (500gm)", 280],
      ["cool cake (1kg)", 500],
      ["egg less cake (500gm)", 180],
      ["egg less cake (1kg)", 350],
      ["photo print cool cake (1kg)", 600],
      ["photo print normal cake (1kg)", 450],
      ["plain cake (250gm)", 60],
      ["plain cake (500gm)", 120],
      ["plain cake (1kg)", 240],
      ["plain cake chocolate (250gm)", 70],
      ["plain cake chocolate (500gm)", 140],
      ["plain cake (1kg)", 280],
      ["banana cake (250gm)", 70],
      ["banana cake (500gm)", 140],
      ["banana cake (1kg)", 280],
    ],
    portions: [
      ["cool cake piece (vanilla)", 35],
      ["cool cake piece (chocolate)", 40],
      ["cool cake piece (butterscotch)", 40],
      ["normal cake piece (pineapple)", 20],
      ["normal cake piece (strawberry)", 20],
      ["normal cake piece (chocolate)", 20],
      [
        "normal cake piece (all flavours) except (pineapple, strawberry, chocolate)",
        10,
      ],
    ],
    puffs: [
      ["egg puff (half)", 15],
      ["egg puff (full)", 20],
      ["veg curry puff (half)", 15],
      ["veg curry puff (full)", 15],
      ["chiili puff", 30],
    ],
    rolls: [
      ["vanilla cake roll", 15],
      ["chocolate cake roll", 15],
      ["dil pasand piece", 10],
      ["dil pasand roll (full)", 40],
    ],
  },
};
